import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./storeProvider"; // ✅ use your StoreProvider here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased outfit ">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
